platform :ios, '10.0'
inhibit_all_warnings!

target 'Demo' do
  use_frameworks!
  
#  pod 'PermissionKit/Core', :path => "../"
#  pod 'PermissionKit/Alert', :path => "../"
#  pod 'PermissionKit/Location', :path => "../"
  pod 'PermissionKit', :path => "../"

end
